sudo: false
language: c
compiler: gcc
script:
- cd skarnet-builder && ./build-wrapper
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "XX12PnEbC96mR/TFOGFlnpN6XhMhBzcdotBg1rfL1fUI2qCFKNxPf73583iMep9XXViIoJ0p2JUuK/GOm3oK02zWblruAJFCNI572X4BKZ/IaXpkCS90DWAQB5EkDFeF9XVdk3/00inFbhkWFB8q5xQNXECgQPXNSbz65kxGxjw="
  file: $HOME/dist/*
  file:
    - $HOME/dist/manifest*.txt
    - $HOME/dist/*.tar.gz
  file_glob: true
  on:
    repo: just-containers/skaware-builder
    branch: master
    tags: true
